Ecommerce/ecommerceproject/cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('remove-all/<int:product_id>/', views.cart_remove_all, name='cart_remove_all'),
]

Ecommerce/ecommerceproject/ecommerceproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('search/', include('search_app.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Ecommerce/ecommerceproject/search_app/urls.py
from django.urls import path
from . import views
app_name = 'search_app'
urlpatterns = [
    path('', views.search_results, name='search_results'),
]

Ecommerce/ecommerceproject/shop/urls.py
from django.urls import path
from . import views
app_name = 'shop'

urlpatterns = [
    path('', views.allprdctct, name='allprdctct'),
    path('<slug:c_slug>/', views.allprdctct, name='products_by_category'),
    path('<slug:c_slug>/<slug:p_slug>/', views.productdetail, name='productdetail'),
]

Ecommerce/ecommerceproject/cart/models.py
from django.db import models
from shop.models import product


# Create your models here.


class Cart(models.Model):
    cart_id = models.CharField(max_length=250)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'cart_id'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    product = models.ForeignKey(product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    QUANTITY = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.QUANTITY

    def __str__(self):
        return '{}'.format(self.product)

Ecommerce/ecommerceproject/search_app/models.py
from django.db import models

# Create your models here.

Ecommerce/ecommerceproject/shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class category(models.Model):
    name=models.CharField(max_length=250, unique=True)
    slug=models.SlugField(max_length=250, unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category', blank=True)
    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'
    def get_url(self):
        return reverse('shop:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)
class product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2,)
    category=models.ForeignKey(category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'

    def get_url(self):
        return reverse('shop:productdetail', args=[self.category.slug,self.slug])
    def __str__(self):
        return '{}'.format(self.name)

Ecommerce/ecommerceproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Cart, CartItem
from shop.models import product
from django.core.exceptions import ObjectDoesNotExist


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    Product = product.objects.get(id=product_id)

    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=Product, cart=cart)
        if cart_item.QUANTITY < cart_item.product.stock:
            cart_item.QUANTITY += 1

        cart_item.save()

    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=Product, cart=cart, QUANTITY=1)
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_item=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.QUANTITY)
            counter += cart_item.QUANTITY
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    Product = get_object_or_404(product, id=product_id)
    cart_item = CartItem.objects.get(product=Product, cart=cart)
    if cart_item.QUANTITY > 1:
        cart_item.QUANTITY -= 1
        cart_item.save()

    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def cart_remove_all(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    Product = get_object_or_404(product, id=product_id)
    cart_item = CartItem.objects.get(product=Product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

Ecommerce/ecommerceproject/search_app/views.py
from django.shortcuts import render
from django.db.models.query import Q
from shop.models import product


def search_results(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request, 'search.html', {'query': query, 'products': products})

Ecommerce/ecommerceproject/shop/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import category, product
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.db.models.query import Q


# Create your views here.

def allprdctct(request, c_slug=None):
    c_page = None
    Products_list = None
    if c_slug != None:
        c_page = get_object_or_404(category, slug=c_slug)
        Products_list = product.objects.all().filter(category=c_page, available=True)
    else:
        Products_list = product.objects.all().filter(available=True)
    pageinator = Paginator(Products_list, 6)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        Products = pageinator.page(page)
    except (EmptyPage, InvalidPage):
        Products = pageinator.page(pageinator.num_pages)

    img = category.objects.all()

    return render(request, 'category.html', {'category': c_page, 'products': Products,'img':img})


def productdetail(request, c_slug, p_slug):

    try:
        Product = product.objects.get(category__slug=c_slug, slug=p_slug)

    except Exception as e:
        raise e


    return render(request, 'product.html', {'product': Product})

Ecommerce/ecommerceproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <link href=" {% static 'css/custom.css' %} " rel="stylesheet">
     <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
     <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content={% block metadescrition %}{% endblock %}>
    <title>{% block title %}{% endblock %}</title>
</head>
<body style="background-color: #FDFEFE; font-family: 'Poppins', sans-serif;">
<div class="container">
    {% include 'header.html' %}
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}
</div>
    {% include 'footer.html' %}
    <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

Ecommerce/ecommerceproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    This is cart page
{% endblock %}
{% block title %}
    Cart
{% endblock %}
{% block content %}
{% if not cart_items %}
    <div>
        <div class="text-center"><br>
            <h1 class="text-center my_title">Your shopping cart is empty</h1>
            <br>
            <p class="text-center">
                please click<a href="{% url 'shop:allprdctct' %}">here</a> to continue shopping
            </p>
        </div>
    </div>
{% else %}
    <div>
        <div class="text-center"><br>
            <h1 class="text-center my_title">Your shopping cart</h1><br>
        </div>
        <div class="row mx-auto">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <table class="table my_custom_table">
                    <thead class="my_custom_thead">
                    <tr>
                        <th colspan="5">Your Items</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for cart_item in cart_items %}
                        <tr>
                            <td>
                                <a href="{{cart_item.product.get_url}}"> <img src="{{cart_item.product.image.url}}" alt="pduct" class="float-left" width="100" height="auto" > </a>
                            </td>
                            <td class="text-left">
                                {{cart_item.product.name}}
                                <br> <br>
                                SKU:{{cart_item.product.id}}
                                <br> <br>
                                Price:₹{{cart_item.product.price}}
                                <br> <br>
                                Quantity:{{cart_item.QUANTITY}} x ₹{{cart_item.product.price}}
                            </td>
                            <td>
                                ₹{{cart_item.sub_total}}
                            </td>
                        {% if cart_item.QUANTITY < cart_item.product.stock %}

                            <td>
                                <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"> <i class="fa fa-plus custom_icon"></i></a>
                                <br><br><a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                                <br><br><a href="{% url 'cart:cart_remove_all' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>
                            </td>
                        {% else %}
                            <td>
                                <br><br><a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                                <br><br><a href="{% url 'cart:cart_remove_all' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>
                            </td>
                        {% endif %}

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                    <table class="table my_custom_table">
                        <thead class="my_custom_thead">
                        <tr>
                            <th>
                                Checkout
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                                Please review your cart items before proceeding with the order payment
                            </td>
                        </tr>
                        <tr>
                            <td class="text-center">
                                Your total is <strong style="font-size:20px">₹{{total}}<strong>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    <div class="mx-auto">
                        <a href="{% url 'shop:allprdctct' %}" class="btn btn-secondary btn-block my_custom_btn" >Continue shopping</a>
                    </div>
                </div>
        </div>
    </div>
{% endif %}
{% endblock %}

Ecommerce/ecommerceproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  {% if category %}
    {{category.description|truncatewords:155}}
  {% else %}
      Welcome
  {% endif %}
{% endblock %}
{% block title %}
  {% if category %}
    {{category.name}} - E kart
  {% else %}
      see our new collections
  {% endif %}
{% endblock %}
{% block content %}
    {% if category %}
    <div>
      <div class="row my_row_class">
          <div class="mx-auto">
            <p><a href="{% url 'shop:allprdctct' %}">OUR PRODUCTS</a></p>
          </div>
      </div>
    </div>
    {% endif %}
    <div class="mx_auto">
      {% if category %}
        <img class="my_image" src="{{category.image.url}}" width="100%" height="auto" alt="{{category.name}}">
        </div><br>
        <div>
          <h1 class="text-center my_title">{{category.name}}</h1>
          <p class="text-justify">{{category.description}}</p>
        </div>
      {% else %}
        <div>
            <img class="my_image my_image_padding" src="{% static 'img/Smartcat_banner.png' %}" alt="our products">
        </div><br>
        <div>
          <h1 class="text-center my_title">Our product collections</h1>
          <p class="text-justify">is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
        </div>
      {% endif %}
<div class="contaier">
  <div class="row mx_auto">
      {% for product in products.object_list %}
      <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xom-lg-4">
        <div class="card text-center" style="min-width:18rem;">
          <a href="{{product.get_url}}"><img class="card-img-top" style="width:50%;height:auto;object-fit:cover;" src="{{product.image.url}}" alt="{{product.name}}"></a>
        <div class="card-body">
            <h4>{{product.name}}</h4>
            <p>{{product.price}}</p>
        </div>
        </div>
      </div>
      {% endfor %}
  </div>
    <div class="mx-auto">
    {% if products.paginator.num_pages > 1 %}
        <br>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
    {% endif %}
    </div>
    <br>
</div>




{% endblock %}

Ecommerce/ecommerceproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <p class="text-center">
    ©Smart cart pvt ltd all rights reserved
  </p>
</div>

Ecommerce/ecommerceproject/templates/header.html
{% load static %}
<header>
  <center>
    <a href="{% url 'shop:allprdctct' %}"><img src="{% static 'img/E-commerce Store_logo.png' %}" width="100px" height="100px" alt="logimage"></a>
  </center>
</header>

Ecommerce/ecommerceproject/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown {% if 'shop' in request.path %} Active {% endif %}">
        <a role="button" type="button" class="btn dropdown" data-toggle="dropdown">
          <i class="fa fa-list" style="font-size:30px;color:#196F3D; aria-hidden="true"></i>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
<!--          <a class="dropdown-item" href="{% url 'shop:allprdctct' %}">ALL PRODUCTS</a>-->
          {% for cat in links %}
          <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
          {% endfor %}

        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'shop:allprdctct' %}">
          <i class="fa fa-home" style="font-size:30px;color:#196F3D;"></i></i></a>
      </li>
      {% if count > 0 %}
      <li class="nav-item">
        <a class="nav-link enabled" href="{% url 'cart:cart_detail' %}"><i class="fa fa-cart-arrow-down"  style="font-size:30px;color:orange;" ></i></i></i><span class='badge badge-warning 'id='lblCartCount' >{{count}}</span></a>
      </li>
      {% elif count == 0 %}
      <li class="nav-item">
        <a class="nav-link disabled" href="{% url 'cart:cart_detail' %}"><i class="fa fa-cart-arrow-down"  style="font-size:30px;color:#196F3D;" ></i></i></i></a>
      </li>
      {% endif %}
    </ul>


    <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'search_app:search_results' %}">
      {% csrf_token %}
      <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa fa-search"></i></button>
    </form>
  </div>
</nav>

Ecommerce/ecommerceproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{product.description|truncatewords:155}}
{% endblock %}
{% block title %}
    {{product.name}} - E kart

      see our new collections
{% endblock %}
{% block content %}
<div class="row my_prdct_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'shop:allprdctct' %}">Home</a>| <a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}} </a></p>
    </div>
</div>
<div class="conatainer">
    <div class="row">
        <div class="col-12 col-sm-12 col-md 12 col-lg-6 text-center">
            <div style="min-width:18rem">
            <img src="{{product.image.url}}" alt="{{product.name}}">
            </div><br>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
            <h1 class="my_prdct_title">{{product.name}}</h1>
            <p>{{product.price}}</p>
                {% if product.stock <= 0 %}
                    <p class="text-justify my_prdct_text" style="color:red;"><b>OUT OF STOCK</b> </p>
                    <a class="btn btn-warning" href="#">NOTIFY ME</a>
                {% else %}
                    <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">ADD TO CART</a>
                {% endif %}
                <br><br>
            <p class="my_title">Product Description</p>
            <p class="text-justify my_prdct_text">{{product.description}}</p>
            </div><br>
        </div>
    </div>
</div>

{% endblock %}

Ecommerce/ecommerceproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    we have variety of products
{% endblock %}

{% block title %}
    search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_serach_text">You have searched for<b>"{{query}}"</b> </p>
</div>

<div class="contaier">
  <div class="row mx_auto">
      {% for product in products %}
      <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xom-lg-4">
        <div class="card text-center" style="min-width:18rem;">
          <a href="{{product.get_url}}"><img class="card-img-top" style="width:50%;height:auto;object-fit:cover;" src="{{product.image.url}}" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>
        </div>
      </div>
      {% empty %}
        <div class="row mx-auto">
        <p class="text-center my_serach_text"> 0 results found</p>
        </div>
      {% endfor %}
  </div>
</div>


{% endblock %}